anatomicalTemplate  :  /home/data/Projects/Zhen/hematocrit/data/%s/%s/anat/anat.nii.gz 

functionalTemplate  :  /home/data/Projects/Zhen/hematocrit/data/%s/%s/rest/rest.nii.gz 

subjectList  :  /home/data/Projects/Zhen/hematocrit/data/Rockland/subList_ultraclearn47sub_poster.txt 

exclusionSubjectList  :  None 

siteList  :  None 

scanParametersCSV  :  None 

outputSubjectListLocation  :  /home/data/Projects/Zhen/hematocrit/hematocrit_code/Rockland/CPAC 

